2022/05/05 23:24:47 [notice] 9196#5428: signal process started
2022/05/05 23:26:07 [error] 10036#10304: *1 CreateFile() "C:\nginx-1.20.2/html/favicon.ico" failed (2: The system cannot find the file specified), client: 192.168.100.212, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.100.212", referrer: "http://192.168.100.212/"
2022/05/06 00:08:22 [notice] 2804#1828: signal process started
2022/05/06 00:19:38 [notice] 11108#1328: signal process started
2022/05/08 22:52:11 [notice] 2756#5716: signal process started
2022/05/08 22:52:52 [error] 8924#2132: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 22:52:53 [error] 8924#2132: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 22:53:52 [error] 8924#2132: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 22:53:53 [error] 8924#2132: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 22:54:42 [notice] 2532#6788: signal process started
2022/05/08 22:55:14 [error] 8924#2132: *10 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 22:55:15 [error] 8924#2132: *10 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 22:55:48 [notice] 2868#6228: signal process started
2022/05/08 22:55:57 [error] 8924#2132: *10 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 22:55:58 [error] 8924#2132: *10 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 22:56:01 [error] 8924#2132: *10 no live upstreams while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "192.168.100.212"
2022/05/08 22:57:02 [notice] 8756#7216: signal process started
2022/05/08 22:57:08 [error] 8924#2132: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 22:57:09 [error] 8924#2132: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 23:00:44 [notice] 8576#424: signal process started
2022/05/08 23:00:54 [error] 8924#2132: *20 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 23:00:55 [error] 8924#2132: *20 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 23:02:14 [error] 8924#2132: *24 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "192.168.100.212"
2022/05/08 23:02:15 [error] 8924#2132: *24 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.100.212, server: testing123, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "192.168.100.212"
2022/05/08 23:02:23 [notice] 492#3816: signal process started
2022/05/08 23:02:47 [notice] 8228#11016: signal process started
2022/05/08 23:29:09 [notice] 6284#1232: signal process started
2022/05/08 23:29:35 [error] 5040#3884: *1 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/html/favicon.ico" failed (2: The system cannot find the file specified), client: 192.168.100.212, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.100.212", referrer: "http://192.168.100.212/"
2022/05/08 23:36:43 [notice] 4488#6616: signal process started
2022/05/08 23:37:32 [notice] 1764#6216: signal process started
2022/05/08 23:37:33 [notice] 6584#2320: signal process started
2022/05/08 23:37:36 [notice] 6420#6536: signal process started
2022/05/09 01:47:52 [emerg] 7072#3592: unexpected "}" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:110
2022/05/09 01:47:57 [emerg] 6800#6228: unexpected "}" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:110
2022/05/09 01:48:21 [emerg] 3996#3188: unexpected "}" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:110
2022/05/09 01:48:40 [notice] 1780#2780: signal process started
2022/05/09 01:48:58 [error] 3276#4476: *3 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/05/09 01:55:39 [error] 3276#4476: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "localhost:10"
2022/05/09 01:55:39 [error] 3276#4476: *16 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:10", referrer: "http://localhost:10/"
2022/05/09 01:55:52 [error] 3276#4476: *16 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:10", referrer: "http://localhost:10/"
2022/05/09 02:02:53 [notice] 3992#1220: signal process started
2022/05/09 02:04:15 [error] 4784#2432: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:8002/", host: "localhost:10"
2022/05/09 02:04:16 [error] 4784#2432: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8002/", host: "localhost:10"
2022/05/09 02:04:44 [notice] 3908#6448: signal process started
2022/05/09 02:04:52 [error] 2036#808: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "localhost:10"
2022/05/09 02:04:52 [error] 2036#808: *1 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:10", referrer: "http://localhost:10/"
2022/05/09 02:06:09 [error] 2036#808: *9 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:10", referrer: "http://localhost:10/"
2022/05/09 02:08:56 [error] 2036#808: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/dataingester/bhom/close/", host: "localhost:10", referrer: "http://localhost:8080/"
2022/05/09 02:09:10 [error] 2036#808: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/dataingester/bhom/close/", host: "localhost:10", referrer: "http://localhost:8080/"
2022/05/09 02:10:33 [notice] 3632#5904: signal process started
2022/05/09 02:10:33 [error] 3632#5904: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 02:10:48 [notice] 5512#896: signal process started
2022/05/09 02:10:48 [error] 5512#896: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 02:11:20 [notice] 5820#4816: signal process started
2022/05/09 02:11:20 [error] 5820#4816: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 02:28:06 [error] 2368#6180: *9 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.0e345ea4.js.map" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.0e345ea4.js.map HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/09 02:46:20 [error] 2368#6180: *12 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.0e345ea4.js.map" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.0e345ea4.js.map HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/09 02:55:09 [notice] 1828#5868: signal process started
2022/05/09 02:55:48 [error] 3276#5772: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: example-test.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "localhost:10"
2022/05/09 02:55:49 [error] 3276#5772: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: example-test.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "localhost:10"
2022/05/09 02:56:57 [error] 4708#4648: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: example-test.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "localhost:10"
2022/05/09 02:56:58 [error] 4708#4648: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: example-test.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "localhost:10"
2022/05/09 02:58:22 [notice] 5252#5772: signal process started
2022/05/09 03:00:01 [notice] 6924#2852: signal process started
2022/05/09 03:00:42 [notice] 2060#4432: signal process started
2022/05/09 16:26:18 [error] 3908#2616: *28 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: www.examplebmc.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "127.0.0.1:10"
2022/05/09 16:26:19 [error] 3908#2616: *28 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: www.examplebmc.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "127.0.0.1:10"
2022/05/09 16:26:19 [error] 3908#2616: *28 no live upstreams while connecting to upstream, client: 127.0.0.1, server: www.examplebmc.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "127.0.0.1:10", referrer: "http://127.0.0.1:10/"
2022/05/09 21:19:04 [notice] 8036#7812: signal process started
2022/05/09 21:21:13 [error] 7116#4784: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /react/ HTTP/1.1", upstream: "http://[::1]:8001/react/", host: "127.0.0.1:8080"
2022/05/09 21:38:36 [notice] 2520#7988: signal process started
2022/05/09 23:12:28 [notice] 6324#7560: signal process started
2022/05/09 23:12:36 [error] 4464#7292: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "localhost:8080"
2022/05/09 23:13:44 [error] 4464#7292: *11 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:8001/", host: "mobility177-rsso3.trybmc.com"
2022/05/09 23:14:11 [error] 4464#7292: *22 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET //dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001//dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/09 23:16:10 [error] 4464#7292: *31 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST //dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001//dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/09 23:27:26 [notice] 684#7944: signal process started
2022/05/09 23:27:26 [error] 684#7944: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 23:28:55 [notice] 7708#3860: signal process started
2022/05/09 23:28:55 [error] 7708#3860: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 23:31:19 [notice] 3644#200: signal process started
2022/05/09 23:31:19 [error] 3644#200: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 23:31:41 [notice] 2860#2636: signal process started
2022/05/09 23:31:41 [error] 2860#2636: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 23:32:05 [notice] 7080#236: signal process started
2022/05/09 23:32:05 [error] 7080#236: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/09 23:33:05 [error] 6612#5788: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", upstream: "http://[::1]:8001/django/", host: "localhost:8080"
2022/05/09 23:44:13 [error] 6612#5788: *10 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", upstream: "http://[::1]:8001/django/", host: "localhost:8080"
2022/05/09 23:49:31 [notice] 4404#3888: signal process started
2022/05/09 23:56:36 [notice] 1032#592: signal process started
2022/05/09 23:57:43 [notice] 6896#2752: signal process started
2022/05/09 23:59:30 [emerg] 488#6948: unknown "proxy_add_xforwarded_for" variable
2022/05/10 00:01:18 [notice] 7252#5800: signal process started
2022/05/10 00:02:18 [notice] 7284#7472: signal process started
2022/05/10 00:04:32 [notice] 7668#6584: signal process started
2022/05/10 00:05:47 [notice] 5952#5552: signal process started
2022/05/10 00:08:21 [notice] 3880#6436: signal process started
2022/05/10 00:08:31 [error] 7924#3224: *1 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:8002", referrer: "http://localhost:8002/"
2022/05/10 00:08:52 [notice] 6376#5980: signal process started
2022/05/10 00:09:29 [error] 1896#6508: *1 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: test.host, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:8002", referrer: "http://localhost:8002/"
2022/05/10 00:09:31 [error] 1896#6508: *1 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: test.host, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:8002", referrer: "http://localhost:8002/"
2022/05/10 00:09:46 [notice] 2276#7380: signal process started
2022/05/10 00:09:46 [error] 2276#7380: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/10 00:27:33 [notice] 408#5136: signal process started
2022/05/10 00:27:33 [error] 408#5136: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/10 00:28:20 [error] 6680#3144: *4 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: _, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "localhost:8002", referrer: "http://localhost:8002/"
2022/05/10 00:28:34 [error] 6680#3144: *8 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Backend\DjangoServer\static/static/admin/css/fonts.css" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: _, request: "GET /static/admin/css/fonts.css HTTP/1.1", host: "127.0.0.1:8002", referrer: "http://127.0.0.1:8002/"
2022/05/10 01:29:20 [notice] 7552#7804: signal process started
2022/05/10 01:34:35 [emerg] 408#3036: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:34:37 [emerg] 7632#5748: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:36:16 [emerg] 7744#7756: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:36:18 [emerg] 8000#7348: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:36:34 [emerg] 3356#6396: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:36:34 [alert] 7340#6496: worker process 3356 exited with code 1
2022/05/10 01:36:34 [alert] 7340#6496: could not respawn worker
2022/05/10 01:36:43 [emerg] 7568#7780: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:37:09 [emerg] 6876#7532: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:37:59 [emerg] 4132#6376: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:38:32 [emerg] 2996#5124: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:38:50 [emerg] 7564#6068: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:38:52 [emerg] 1628#8076: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:38:54 [emerg] 6800#456: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:41:50 [notice] 7876#1792: signal process started
2022/05/10 01:47:29 [emerg] 1560#7848: "proxy_pass" directive is not allowed here in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:109
2022/05/10 01:48:35 [notice] 5164#6708: signal process started
2022/05/10 01:49:08 [notice] 5080#476: signal process started
2022/05/10 02:02:27 [notice] 3224#1500: signal process started
2022/05/10 02:02:27 [error] 3224#1500: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/10 02:02:41 [error] 1512#3356: *6 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET //dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 02:02:41 [error] 1512#3356: *7 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET //dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 02:02:41 [error] 1512#3356: *8 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET //dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 02:02:41 [error] 1512#3356: *9 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET //dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 02:02:53 [error] 1512#3356: *11 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:05:07 [notice] 5300#6768: signal process started
2022/05/10 02:05:11 [error] 1512#3356: *13 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:06:21 [notice] 6344#3736: signal process started
2022/05/10 02:06:26 [error] 1512#3356: *16 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:06:31 [error] 1512#3356: *16 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET /static/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:08:52 [notice] 3840#7648: signal process started
2022/05/10 02:08:57 [error] 1512#3356: *19 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET /static/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:09:05 [error] 1512#3356: *19 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:10:14 [notice] 7592#6784: signal process started
2022/05/10 02:10:25 [error] 1512#3356: *22 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:10:27 [error] 1512#3356: *22 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:11:25 [notice] 4796#5172: signal process started
2022/05/10 02:11:30 [error] 1512#3356: *22 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:12:00 [error] 1512#3356: *22 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:24:16 [error] 1512#3356: *26 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:24:35 [error] 1512#3356: *26 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:24:50 [error] 1512#3356: *26 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:28:03 [notice] 2528#7688: signal process started
2022/05/10 02:28:11 [error] 1512#3356: *29 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /django/ HTTP/1.1", host: "localhost:8080"
2022/05/10 02:29:47 [error] 1512#3356: *36 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/django" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /django HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/10 02:29:59 [error] 1512#3356: *37 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/test" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /test HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/10 02:30:03 [error] 1512#3356: *38 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/test" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /test HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/10 02:30:08 [error] 1512#3356: *39 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/hi" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /hi HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/10 02:46:56 [notice] 4600#5948: signal process started
2022/05/10 02:47:19 [notice] 7552#6888: signal process started
2022/05/10 02:52:33 [notice] 3220#7340: signal process started
2022/05/10 02:54:45 [notice] 7288#5408: signal process started
2022/05/10 04:09:22 [error] 2920#7004: *197 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:09:22 [error] 2920#7004: *198 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:09:22 [error] 2920#7004: *199 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:09:22 [error] 2920#7004: *200 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:17:29 [error] 2920#7004: *355 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:17:29 [error] 2920#7004: *356 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:17:29 [error] 2920#7004: *357 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 04:17:29 [error] 2920#7004: *358 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 05:06:34 [error] 2920#7004: *629 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 05:06:35 [error] 2920#7004: *631 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 05:06:36 [error] 2920#7004: *633 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 05:06:38 [error] 2920#7004: *635 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 05:07:54 [error] 2920#7004: *637 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 05:07:54 [error] 2920#7004: *638 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 05:07:54 [error] 2920#7004: *639 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 05:07:54 [error] 2920#7004: *640 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 05:08:11 [error] 2920#7004: *643 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 05:08:12 [error] 2920#7004: *646 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 05:08:13 [error] 2920#7004: *648 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 05:08:14 [error] 2920#7004: *650 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 10:11:14 [error] 2920#7004: *794 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 10:48:41 [error] 2920#7004: *890 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/itsm/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 10:56:52 [error] 2920#7004: *913 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 11:02:30 [error] 2920#7004: *937 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/itsm/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 11:10:57 [error] 2920#7004: *950 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/itsm/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 11:19:11 [error] 2920#7004: *975 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/10 23:12:57 [error] 2920#7004: *1472 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:12:57 [error] 2920#7004: *1473 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:12:57 [error] 2920#7004: *1474 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:12:57 [error] 2920#7004: *1475 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:14:44 [error] 2920#7004: *1512 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.f9afaef1.js.map" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/js/main.f9afaef1.js.map HTTP/1.1", host: "localhost:8080"
2022/05/10 23:14:44 [error] 2920#7004: *1514 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:14:44 [error] 2920#7004: *1515 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:14:44 [error] 2920#7004: *1516 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:14:44 [error] 2920#7004: *1517 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:15:18 [error] 2920#7004: *1519 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:15:18 [error] 2920#7004: *1520 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:15:18 [error] 2920#7004: *1521 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:15:18 [error] 2920#7004: *1522 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:8080/"
2022/05/10 23:15:18 [error] 2920#7004: *1523 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:15:18 [error] 2920#7004: *1524 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:15:18 [error] 2920#7004: *1525 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:15:18 [error] 2920#7004: *1526 "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/djang/dataingester/bhom/close/index.html" is not found (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /djang/dataingester/bhom/close/ HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/10 23:18:10 [error] 2920#7004: *1535 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
2022/05/11 02:02:33 [error] 2920#7004: *1740 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 02:05:18 [error] 2920#7004: *1771 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 02:30:31 [notice] 6924#188: signal process started
2022/05/11 02:31:45 [error] 7240#6076: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 02:34:35 [notice] 3732#4056: signal process started
2022/05/11 02:35:52 [error] 7484#6500: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 02:37:57 [notice] 6416#4312: signal process started
2022/05/11 02:43:00 [notice] 3276#4736: signal process started
2022/05/11 03:04:53 [notice] 4676#4968: signal process started
2022/05/11 03:07:00 [notice] 7756#892: signal process started
2022/05/11 03:08:12 [error] 6360#7660: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:15:07 [notice] 3848#7552: signal process started
2022/05/11 03:15:07 [error] 3848#7552: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 03:15:39 [notice] 6100#452: signal process started
2022/05/11 03:15:39 [error] 6100#452: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 03:17:32 [error] 1452#4312: *20 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:19:02 [error] 1452#4312: *33 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:20:24 [notice] 8144#7360: signal process started
2022/05/11 03:21:36 [error] 7556#2636: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:23:42 [notice] 4132#7320: signal process started
2022/05/11 03:25:40 [error] 7408#7176: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:28:15 [notice] 5380#7188: signal process started
2022/05/11 03:29:29 [error] 2616#6476: *34 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 03:30:58 [notice] 7104#1748: signal process started
2022/05/11 03:33:36 [notice] 6980#4896: signal process started
2022/05/11 03:39:20 [error] 7220#8020: *56 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/11 03:39:22 [error] 7220#8020: *57 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/11 03:39:23 [error] 7220#8020: *58 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/11 04:24:37 [notice] 7452#6092: signal process started
2022/05/11 04:52:08 [notice] 7804#7512: signal process started
2022/05/11 04:54:38 [notice] 452#7356: signal process started
2022/05/11 04:56:02 [notice] 8084#5136: signal process started
2022/05/11 04:56:23 [error] 7560#7188: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 04:56:55 [notice] 8008#7796: signal process started
2022/05/11 04:56:55 [error] 8008#7796: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 04:56:59 [notice] 7556#7956: signal process started
2022/05/11 04:57:17 [error] 7560#7188: *36 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 04:57:44 [notice] 7108#7512: signal process started
2022/05/11 04:58:05 [error] 7560#7188: *71 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 05:05:02 [notice] 2376#7752: signal process started
2022/05/11 05:06:15 [error] 3864#7632: *16 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 05:17:33 [notice] 1568#7176: signal process started
2022/05/11 05:17:38 [notice] 7428#7376: signal process started
2022/05/11 05:17:38 [error] 7428#7376: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 05:25:01 [notice] 3144#8080: signal process started
2022/05/11 05:26:17 [error] 3640#7904: *26 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 06:01:03 [notice] 2440#2612: signal process started
2022/05/11 06:01:24 [notice] 3276#7216: signal process started
2022/05/11 06:02:35 [error] 7764#5668: *16 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 06:02:45 [notice] 8020#6408: signal process started
2022/05/11 06:03:56 [error] 7764#5668: *51 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 09:52:23 [error] 7764#5668: *130 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/11 10:04:34 [notice] 7216#6028: signal process started
2022/05/11 10:07:07 [error] 7764#5668: *167 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:07:08 [notice] 6700#7600: signal process started
2022/05/11 10:08:21 [error] 2376#7856: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:08:42 [notice] 1828#4556: signal process started
2022/05/11 10:14:02 [error] 6888#7296: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:14:59 [notice] 5108#7136: signal process started
2022/05/11 10:16:19 [error] 7728#7716: *26 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:21:27 [emerg] 4936#7636: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:21:33 [emerg] 7844#1520: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:21:46 [emerg] 7796#4216: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:21:46 [alert] 6136#7724: worker process 7796 exited with code 1
2022/05/11 10:21:46 [alert] 6136#7724: could not respawn worker
2022/05/11 10:21:53 [emerg] 2840#2652: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:22:22 [emerg] 3812#7580: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:22:42 [emerg] 3996#812: unknown directive "prxy_http_version" in C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/conf/nginx.conf:114
2022/05/11 10:23:01 [notice] 2540#7984: signal process started
2022/05/11 10:23:01 [error] 2540#7984: OpenEvent("Global\ngx_stop_6136") failed (2: The system cannot find the file specified)
2022/05/11 10:24:44 [notice] 4216#7796: signal process started
2022/05/11 10:25:32 [notice] 6888#2708: signal process started
2022/05/11 10:26:05 [notice] 6460#2588: signal process started
2022/05/11 10:26:07 [notice] 7892#7284: signal process started
2022/05/11 10:26:07 [error] 7892#7284: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 10:27:19 [error] 5408#6416: *13 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:28:32 [notice] 6948#7080: signal process started
2022/05/11 10:30:29 [notice] 4996#7056: signal process started
2022/05/11 10:31:47 [error] 6172#6032: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:33:10 [notice] 7996#7520: signal process started
2022/05/11 10:33:11 [notice] 5136#7580: signal process started
2022/05/11 10:33:11 [error] 5136#7580: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/11 10:34:23 [error] 1828#2920: *23 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:35:01 [notice] 6052#5132: signal process started
2022/05/11 10:36:10 [error] 6168#3864: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/11 10:40:28 [notice] 7584#1544: signal process started
2022/05/12 10:51:12 [notice] 5164#6308: signal process started
2022/05/12 10:51:13 [notice] 8056#1800: signal process started
2022/05/12 10:51:13 [error] 8056#1800: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/12 10:55:02 [notice] 3744#2996: signal process started
2022/05/12 11:01:27 [notice] 5160#3852: signal process started
2022/05/12 11:02:37 [error] 4056#1032: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/12 20:48:25 [notice] 7444#6656: signal process started
2022/05/12 22:23:23 [error] 7080#240: *64 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/12 22:29:07 [notice] 3840#7492: signal process started
2022/05/12 22:29:26 [error] 8176#4744: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/12 22:39:43 [notice] 2660#968: signal process started
2022/05/12 23:23:16 [notice] 7996#7944: signal process started
2022/05/12 23:41:27 [notice] 7200#7316: signal process started
2022/05/12 23:51:24 [notice] 7456#7188: signal process started
2022/05/12 23:53:08 [notice] 1568#2840: signal process started
2022/05/13 00:02:28 [notice] 7604#7592: signal process started
2022/05/13 00:02:28 [error] 7604#7592: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/13 01:02:03 [notice] 5004#3532: signal process started
2022/05/13 01:04:42 [notice] 6156#2004: signal process started
2022/05/13 01:04:44 [notice] 7080#5508: signal process started
2022/05/13 01:04:44 [error] 7080#5508: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/13 01:05:12 [notice] 7016#4060: signal process started
2022/05/13 01:05:12 [error] 7016#4060: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/15 23:53:11 [notice] 6780#5200: signal process started
2022/05/15 23:53:11 [error] 6780#5200: OpenEvent("Global\ngx_stop_7856") failed (2: The system cannot find the file specified)
2022/05/15 23:58:20 [error] 7048#4572: *14 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.7252f82a.js.map" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.7252f82a.js.map HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/16 07:10:32 [notice] 6176#5340: signal process started
2022/05/17 07:21:13 [notice] 5176#6236: signal process started
2022/05/17 07:23:51 [notice] 3556#6928: signal process started
2022/05/17 08:23:58 [notice] 5824#5392: signal process started
2022/05/17 08:24:55 [notice] 5392#5824: signal process started
2022/05/17 08:25:50 [notice] 4264#6624: signal process started
2022/05/17 08:27:03 [notice] 3236#6612: signal process started
2022/05/17 08:27:50 [notice] 6612#3236: signal process started
2022/05/17 08:28:55 [notice] 592#3684: signal process started
2022/05/17 08:29:20 [error] 7140#6468: *10 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:29:47 [notice] 4668#7164: signal process started
2022/05/17 08:30:02 [error] 3348#1056: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:30:46 [error] 3348#1056: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:31:06 [notice] 2388#4656: signal process started
2022/05/17 08:32:13 [error] 3212#5420: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:32:14 [notice] 7152#3208: signal process started
2022/05/17 08:33:21 [error] 5924#6192: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:35:29 [notice] 6468#5224: signal process started
2022/05/17 08:36:41 [error] 3708#3212: *10 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:36:47 [notice] 5544#1884: signal process started
2022/05/17 08:37:53 [error] 6688#5924: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:50:52 [error] 6688#5924: *12 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/17 08:51:46 [notice] 7400#7372: signal process started
2022/05/17 23:20:06 [notice] 1336#5700: signal process started
2022/05/18 00:20:43 [error] 7628#4840: *43 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/18 00:20:46 [error] 7628#4840: *45 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/18 01:20:41 [notice] 1052#8104: signal process started
2022/05/18 01:23:04 [error] 6344#3956: *8 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/18 01:25:38 [error] 6344#3956: *24 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8000/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 01:27:40 [error] 6344#3956: *47 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8000/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 02:00:21 [notice] 7440#7176: signal process started
2022/05/18 02:00:32 [error] 3472#7136: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8000/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 02:00:47 [error] 3472#7136: *19 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8000/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 02:01:26 [notice] 8188#7496: signal process started
2022/05/18 02:07:05 [notice] 2932#6736: signal process started
2022/05/18 03:55:45 [notice] 1620#1944: signal process started
2022/05/18 04:27:51 [notice] 6556#5288: signal process started
2022/05/18 04:28:10 [error] 6888#7856: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "localhost:8080", referrer: "http://localhost:8080/"
2022/05/18 04:28:59 [notice] 5916#7596: signal process started
2022/05/18 04:30:30 [error] 8164#7760: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "localhost:8080", referrer: "http://localhost:8080/"
2022/05/18 04:31:45 [notice] 6580#6420: signal process started
2022/05/18 04:47:35 [error] 5236#7836: *22 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:53:58 [notice] 8916#4592: signal process started
2022/05/18 04:54:04 [notice] 6204#7564: using the "select" event method
2022/05/18 04:54:04 [notice] 6204#7564: using the "select" event method
2022/05/18 04:54:04 [notice] 6204#7564: nginx/1.20.2
2022/05/18 04:54:04 [notice] 6204#7564: nginx/1.20.2
2022/05/18 04:54:04 [info] 6204#7564: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 04:54:04 [notice] 6204#7564: start worker processes
2022/05/18 04:54:04 [notice] 6204#7564: start worker processes
2022/05/18 04:54:04 [notice] 6204#7564: start worker process 8016
2022/05/18 04:54:04 [notice] 6204#7564: start worker process 8016
2022/05/18 04:54:04 [notice] 8016#7816: nginx/1.20.2
2022/05/18 04:54:04 [notice] 8016#7816: nginx/1.20.2
2022/05/18 04:54:04 [info] 8016#7816: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 04:54:04 [notice] 8016#7816: create thread 8160
2022/05/18 04:54:04 [notice] 8016#7816: create thread 8160
2022/05/18 04:54:04 [notice] 8016#7816: create thread 3064
2022/05/18 04:54:04 [notice] 8016#7816: create thread 3064
2022/05/18 04:54:04 [notice] 8016#7816: create thread 4896
2022/05/18 04:54:04 [notice] 8016#7816: create thread 4896
2022/05/18 04:55:18 [warn] 8016#8160: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [warn] 8016#8160: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [warn] 8016#8160: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [error] 8016#8160: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [error] 8016#8160: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [error] 8016#8160: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 04:55:18 [error] 8016#8160: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [warn] 8016#8160: *29 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [warn] 8016#8160: *29 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [warn] 8016#8160: *29 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [error] 8016#8160: *29 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [error] 8016#8160: *29 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [error] 8016#8160: *29 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:21:40 [error] 8016#8160: *29 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [warn] 8016#8160: *44 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [warn] 8016#8160: *44 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [warn] 8016#8160: *44 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [error] 8016#8160: *44 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [error] 8016#8160: *44 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [error] 8016#8160: *44 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:27:10 [error] 8016#8160: *44 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [warn] 8016#8160: *59 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [warn] 8016#8160: *59 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [warn] 8016#8160: *59 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [error] 8016#8160: *59 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [error] 8016#8160: *59 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [error] 8016#8160: *59 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:30:03 [error] 8016#8160: *59 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [warn] 8016#8160: *74 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [warn] 8016#8160: *74 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [warn] 8016#8160: *74 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [error] 8016#8160: *74 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [error] 8016#8160: *74 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [error] 8016#8160: *74 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:31:46 [error] 8016#8160: *74 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:33:19 [notice] 7584#7292: signal process started
2022/05/18 05:33:19 [notice] 6204#7564: exiting
2022/05/18 05:33:19 [notice] 6204#7564: exiting
2022/05/18 05:33:19 [notice] 8016#7816: gracefully shutting down
2022/05/18 05:33:19 [notice] 8016#7816: gracefully shutting down
2022/05/18 05:33:19 [notice] 8016#3064: exiting
2022/05/18 05:33:19 [notice] 8016#3064: exiting
2022/05/18 05:33:20 [notice] 8016#8160: exiting
2022/05/18 05:33:20 [notice] 8016#8160: exiting
2022/05/18 05:33:20 [notice] 8016#7816: exit
2022/05/18 05:33:20 [notice] 8016#7816: exit
2022/05/18 05:33:20 [notice] 6204#7564: worker process 8016 exited with code 0
2022/05/18 05:33:20 [notice] 6204#7564: worker process 8016 exited with code 0
2022/05/18 05:33:20 [notice] 6204#7564: exit
2022/05/18 05:33:20 [notice] 6204#7564: exit
2022/05/18 05:33:20 [notice] 8980#8128: using the "select" event method
2022/05/18 05:33:20 [notice] 8980#8128: using the "select" event method
2022/05/18 05:33:20 [notice] 8980#8128: nginx/1.20.2
2022/05/18 05:33:20 [notice] 8980#8128: nginx/1.20.2
2022/05/18 05:33:20 [info] 8980#8128: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:33:20 [notice] 8980#8128: start worker processes
2022/05/18 05:33:20 [notice] 8980#8128: start worker processes
2022/05/18 05:33:20 [notice] 8980#8128: start worker process 8428
2022/05/18 05:33:20 [notice] 8980#8128: start worker process 8428
2022/05/18 05:33:20 [notice] 8428#4652: nginx/1.20.2
2022/05/18 05:33:20 [notice] 8428#4652: nginx/1.20.2
2022/05/18 05:33:20 [info] 8428#4652: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:33:20 [notice] 8428#4652: create thread 7988
2022/05/18 05:33:20 [notice] 8428#4652: create thread 7988
2022/05/18 05:33:20 [notice] 8428#4652: create thread 2636
2022/05/18 05:33:20 [notice] 8428#4652: create thread 2636
2022/05/18 05:33:20 [notice] 8428#4652: create thread 8808
2022/05/18 05:33:20 [notice] 8428#4652: create thread 8808
2022/05/18 05:35:04 [warn] 8428#7988: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [warn] 8428#7988: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [warn] 8428#7988: *14 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [error] 8428#7988: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [error] 8428#7988: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [error] 8428#7988: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:35:04 [error] 8428#7988: *14 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:36:39 [notice] 8408#9204: signal process started
2022/05/18 05:36:39 [notice] 8980#8128: exiting
2022/05/18 05:36:39 [notice] 8980#8128: exiting
2022/05/18 05:36:39 [notice] 8428#4652: gracefully shutting down
2022/05/18 05:36:39 [notice] 8428#4652: gracefully shutting down
2022/05/18 05:36:39 [notice] 8428#2636: exiting
2022/05/18 05:36:39 [notice] 8428#2636: exiting
2022/05/18 05:36:39 [notice] 8428#7988: exiting
2022/05/18 05:36:39 [notice] 8428#7988: exiting
2022/05/18 05:36:39 [notice] 8428#4652: exit
2022/05/18 05:36:39 [notice] 8428#4652: exit
2022/05/18 05:36:39 [notice] 8980#8128: worker process 8428 exited with code 0
2022/05/18 05:36:39 [notice] 8980#8128: worker process 8428 exited with code 0
2022/05/18 05:36:39 [notice] 8980#8128: exit
2022/05/18 05:36:39 [notice] 8980#8128: exit
2022/05/18 05:36:39 [notice] 6652#8436: using the "select" event method
2022/05/18 05:36:39 [notice] 6652#8436: using the "select" event method
2022/05/18 05:36:39 [notice] 6652#8436: nginx/1.20.2
2022/05/18 05:36:39 [notice] 6652#8436: nginx/1.20.2
2022/05/18 05:36:39 [info] 6652#8436: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:36:39 [notice] 6652#8436: start worker processes
2022/05/18 05:36:39 [notice] 6652#8436: start worker processes
2022/05/18 05:36:39 [notice] 6652#8436: start worker process 8836
2022/05/18 05:36:39 [notice] 6652#8436: start worker process 8836
2022/05/18 05:36:40 [notice] 8836#6780: nginx/1.20.2
2022/05/18 05:36:40 [notice] 8836#6780: nginx/1.20.2
2022/05/18 05:36:40 [info] 8836#6780: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:36:40 [notice] 8836#6780: create thread 5168
2022/05/18 05:36:40 [notice] 8836#6780: create thread 5168
2022/05/18 05:36:40 [notice] 8836#6780: create thread 7768
2022/05/18 05:36:40 [notice] 8836#6780: create thread 7768
2022/05/18 05:36:40 [notice] 8836#6780: create thread 7348
2022/05/18 05:36:40 [notice] 8836#6780: create thread 7348
2022/05/18 05:37:52 [warn] 8836#5168: *23 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [warn] 8836#5168: *23 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [warn] 8836#5168: *23 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [error] 8836#5168: *23 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [error] 8836#5168: *23 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [error] 8836#5168: *23 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:37:52 [error] 8836#5168: *23 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [warn] 8836#5168: *38 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [warn] 8836#5168: *38 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [warn] 8836#5168: *38 upstream server temporarily disabled while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [error] 8836#5168: *38 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [error] 8836#5168: *38 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [error] 8836#5168: *38 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:42:34 [error] 8836#5168: *38 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/18 05:43:14 [notice] 7796#9144: signal process started
2022/05/18 05:43:14 [notice] 6652#8436: exiting
2022/05/18 05:43:14 [notice] 6652#8436: exiting
2022/05/18 05:43:14 [notice] 8836#6780: gracefully shutting down
2022/05/18 05:43:14 [notice] 8836#6780: gracefully shutting down
2022/05/18 05:43:14 [notice] 8836#7768: exiting
2022/05/18 05:43:14 [notice] 8836#7768: exiting
2022/05/18 05:43:14 [notice] 8836#5168: exiting
2022/05/18 05:43:14 [notice] 8836#5168: exiting
2022/05/18 05:43:14 [notice] 8836#6780: exit
2022/05/18 05:43:14 [notice] 8836#6780: exit
2022/05/18 05:43:14 [notice] 6652#8436: worker process 8836 exited with code 0
2022/05/18 05:43:14 [notice] 6652#8436: worker process 8836 exited with code 0
2022/05/18 05:43:14 [notice] 6652#8436: exit
2022/05/18 05:43:14 [notice] 6652#8436: exit
2022/05/18 05:43:15 [notice] 9100#8760: using the "select" event method
2022/05/18 05:43:15 [notice] 9100#8760: using the "select" event method
2022/05/18 05:43:15 [notice] 9100#8760: nginx/1.20.2
2022/05/18 05:43:15 [notice] 9100#8760: nginx/1.20.2
2022/05/18 05:43:15 [info] 9100#8760: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:43:15 [notice] 9100#8760: start worker processes
2022/05/18 05:43:15 [notice] 9100#8760: start worker processes
2022/05/18 05:43:15 [notice] 9100#8760: start worker process 5196
2022/05/18 05:43:15 [notice] 9100#8760: start worker process 5196
2022/05/18 05:43:15 [notice] 5196#8704: nginx/1.20.2
2022/05/18 05:43:15 [notice] 5196#8704: nginx/1.20.2
2022/05/18 05:43:15 [info] 5196#8704: OS: 260200 build:9200, "", suite:110, type:3
2022/05/18 05:43:15 [notice] 5196#8704: create thread 8160
2022/05/18 05:43:15 [notice] 5196#8704: create thread 8160
2022/05/18 05:43:15 [notice] 5196#8704: create thread 7732
2022/05/18 05:43:15 [notice] 5196#8704: create thread 7732
2022/05/18 05:43:15 [notice] 5196#8704: create thread 7660
2022/05/18 05:43:15 [notice] 5196#8704: create thread 7660
2022/05/18 22:00:23 [notice] 688#7136: signal process started
2022/05/18 22:00:23 [notice] 9100#8760: exiting
2022/05/18 22:00:23 [notice] 9100#8760: exiting
2022/05/18 22:00:23 [notice] 5196#8704: gracefully shutting down
2022/05/18 22:00:23 [notice] 5196#8704: gracefully shutting down
2022/05/18 22:00:23 [notice] 5196#7732: exiting
2022/05/18 22:00:23 [notice] 5196#7732: exiting
2022/05/18 22:00:23 [notice] 5196#8160: exiting
2022/05/18 22:00:23 [notice] 5196#8160: exiting
2022/05/18 22:00:23 [notice] 5196#8704: exit
2022/05/18 22:00:23 [notice] 5196#8704: exit
2022/05/18 22:00:23 [notice] 9100#8760: worker process 5196 exited with code 0
2022/05/18 22:00:23 [notice] 9100#8760: worker process 5196 exited with code 0
2022/05/18 22:00:23 [notice] 9100#8760: exit
2022/05/18 22:00:23 [notice] 9100#8760: exit
2022/05/19 21:25:46 [error] 7108#2036: *432 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/itsm/close/", host: "mobility177-rsso3.trybmc.com", referrer: "http://localhost:3000/"
2022/05/19 21:53:10 [error] 7108#2036: *497 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.16f34f17.js.map" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.16f34f17.js.map HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/19 21:54:19 [error] 7108#2036: *509 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/itsm/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/19 21:59:04 [error] 7108#2036: *521 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/19 21:59:59 [error] 7108#2036: *533 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/19 22:00:33 [notice] 8988#6208: signal process started
2022/05/19 22:04:04 [error] 9040#7844: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/19 22:04:58 [notice] 7144#3084: signal process started
2022/05/19 22:06:29 [error] 6420#7488: *11 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/19 22:07:15 [notice] 4928#8748: signal process started
2022/05/23 01:42:36 [error] 8340#5188: *307 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/23 08:35:13 [error] 8340#5188: *516 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/23 08:35:14 [error] 8340#5188: *516 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/23 08:35:14 [error] 8340#5188: *521 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/23 08:35:14 [error] 8340#5188: *522 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/23 21:21:09 [error] 8340#5188: *690 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/24 01:40:04 [error] 8340#5188: *794 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.48b95805.js" failed (2: The system cannot find the file specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.48b95805.js HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/25 00:02:47 [error] 8340#5188: *1500 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/25 00:08:44 [error] 8340#5188: *1528 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/js/main.9877e7e9.js" failed (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /static/js/main.9877e7e9.js HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/25 00:08:44 [error] 8340#5188: *1529 CreateFile() "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/static/css/main.b347cd85.css" failed (3: The system cannot find the path specified), client: 192.168.59.14, server: localhost, request: "GET /static/css/main.b347cd85.css HTTP/1.1", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/25 04:02:40 [error] 8340#5188: *1648 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/25 04:02:46 [error] 8340#5188: *1649 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/25 22:24:13 [error] 8340#5188: *1907 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/25 22:24:13 [error] 8340#5188: *1894 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/25 22:24:14 [error] 8340#5188: *1907 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 03:51:52 [error] 8340#5188: *2508 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/26 03:51:53 [error] 8340#5188: *2510 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/26 04:03:59 [error] 8340#5188: *2566 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 05:49:18 [error] 8340#5188: *2834 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/26 05:49:20 [error] 8340#5188: *2835 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/26 05:51:13 [error] 8340#5188: *2848 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/26 06:03:01 [error] 5720#5796: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:03 [error] 5720#5796: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:03 [error] 5720#5796: *9 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:03 [error] 5720#5796: *10 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:52 [error] 5720#5796: *14 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:53 [error] 5720#5796: *14 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:53 [error] 5720#5796: *17 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:03:53 [error] 5720#5796: *18 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:11 [error] 5720#5796: *23 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:12 [error] 5720#5796: *23 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:12 [error] 5720#5796: *27 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:12 [error] 5720#5796: *28 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:14 [error] 5720#5796: *32 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:14 [error] 5720#5796: *33 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:08:14 [error] 5720#5796: *34 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:09:50 [error] 5720#5796: *35 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:09:51 [error] 5720#5796: *35 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:10:10 [error] 5720#5796: *38 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:10:11 [error] 5720#5796: *38 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:11:00 [error] 5720#5796: *41 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:11:01 [error] 5720#5796: *41 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:05 [error] 5720#5796: *44 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:06 [error] 5720#5796: *44 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:07 [error] 5720#5796: *48 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:07 [error] 5720#5796: *49 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:24 [error] 5720#5796: *50 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:25 [error] 5720#5796: *50 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:56 [error] 5720#5796: *58 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:57 [error] 5720#5796: *58 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:57 [error] 5720#5796: *61 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:13:58 [error] 5720#5796: *62 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:14:30 [error] 5720#5796: *63 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:14:31 [error] 5720#5796: *63 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:29:47 [error] 5720#5796: *70 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:29:48 [error] 5720#5796: *70 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:29:48 [error] 5720#5796: *74 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:29:48 [error] 5720#5796: *75 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:02 [error] 5720#5796: *76 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:03 [error] 5720#5796: *76 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:03 [error] 5720#5796: *79 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:03 [error] 5720#5796: *80 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:04 [error] 5720#5796: *82 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:04 [error] 5720#5796: *83 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:04 [error] 5720#5796: *84 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:05 [error] 5720#5796: *85 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:05 [error] 5720#5796: *86 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:30:05 [error] 5720#5796: *87 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:53:27 [error] 5720#5796: *93 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:53:28 [error] 5720#5796: *93 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:53:29 [error] 5720#5796: *96 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/26 06:53:29 [error] 5720#5796: *97 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 02:07:24 [error] 5720#5796: *467 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility177-rsso3.trybmc.com"
2022/05/30 06:07:38 [notice] 6904#6676: signal process started
2022/05/30 06:27:05 [notice] 5300#6340: signal process started
2022/05/30 06:28:31 [notice] 928#5972: signal process started
2022/05/30 06:28:48 [notice] 6396#2880: signal process started
2022/05/30 06:33:47 [notice] 6288#4288: signal process started
2022/05/30 06:33:52 [notice] 3880#6600: signal process started
2022/05/30 06:33:52 [error] 3880#6600: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/30 21:40:08 [notice] 4640#6244: signal process started
2022/05/30 21:40:08 [error] 4640#6244: OpenEvent("Global\ngx_stop_6432") failed (2: The system cannot find the file specified)
2022/05/30 21:40:24 [notice] 5456#5392: signal process started
2022/05/30 21:40:35 [notice] 4948#6640: signal process started
2022/05/30 21:40:35 [error] 4948#6640: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/30 21:40:56 [notice] 5176#2972: signal process started
2022/05/30 21:41:15 [notice] 3876#1792: signal process started
2022/05/30 21:41:15 [error] 3876#1792: CreateFile() "C:\Users\Administrator\Desktop\DataIngester\nginx-1.20.2/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/30 22:09:10 [notice] 2632#2476: signal process started
2022/05/30 22:09:10 [error] 2632#2476: OpenEvent("Global\ngx_stop_2796") failed (2: The system cannot find the file specified)
2022/05/30 22:18:17 [error] 3364#1932: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:18 [error] 3364#1932: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:18 [error] 3364#1932: *9 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:18 [error] 3364#1932: *10 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:22 [error] 3364#1932: *11 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:22 [error] 3364#1932: *12 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:22 [error] 3364#1932: *13 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:31 [error] 3364#1932: *14 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/itsm/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/30 22:18:32 [error] 3364#1932: *14 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/itsm/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/itsm/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:11 [error] 948#2220: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:12 [error] 948#2220: *4 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:13 [error] 948#2220: *9 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:13 [error] 948#2220: *10 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:57 [error] 948#2220: *12 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:58 [error] 948#2220: *12 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:58 [error] 948#2220: *15 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 01:37:59 [error] 948#2220: *16 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 04:46:20 [error] 948#2220: *83 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 04:46:21 [error] 948#2220: *83 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 04:46:21 [error] 948#2220: *87 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/05/31 04:46:21 [error] 948#2220: *88 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility177-rsso3.trybmc.com", referrer: "https://mobility177-rsso3.trybmc.com/"
2022/06/02 13:40:26 [error] 2300#2124: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:27 [error] 2300#2124: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:27 [error] 2300#2124: *11 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:27 [error] 2300#2124: *12 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:39 [error] 2300#2124: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:41 [error] 2300#2124: *16 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:41 [error] 2300#2124: *21 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:41 [error] 2300#2124: *22 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:55 [error] 2300#2124: *25 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:56 [error] 2300#2124: *25 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:57 [error] 2300#2124: *30 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:57 [error] 2300#2124: *31 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:59 [error] 2300#2124: *33 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:59 [error] 2300#2124: *36 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:40:59 [error] 2300#2124: *37 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:01 [error] 2300#2124: *39 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:01 [error] 2300#2124: *42 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:01 [error] 2300#2124: *43 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:11 [error] 2300#2124: *44 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:12 [error] 2300#2124: *44 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:12 [error] 2300#2124: *47 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:41:12 [error] 2300#2124: *48 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:42:40 [error] 2300#2124: *54 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:42:41 [error] 2300#2124: *54 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:42:41 [error] 2300#2124: *57 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:42:42 [error] 2300#2124: *58 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:10 [error] 2300#2124: *60 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:11 [error] 2300#2124: *60 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:12 [error] 2300#2124: *63 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:12 [error] 2300#2124: *64 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:35 [error] 2300#2124: *66 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:44:36 [error] 2300#2124: *66 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:07 [error] 2268#2616: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:08 [error] 2268#2616: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:08 [error] 2268#2616: *13 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:08 [error] 2268#2616: *14 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:08 [error] 2268#2616: *16 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:09 [error] 2268#2616: *18 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:09 [error] 2268#2616: *20 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:27 [error] 2268#2616: *23 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:28 [error] 2268#2616: *23 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:39 [error] 2268#2616: *27 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:40 [error] 2268#2616: *27 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:40 [error] 2268#2616: *32 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:48:40 [error] 2268#2616: *33 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:11 [error] 2268#2616: *35 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:12 [error] 2268#2616: *35 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:12 [error] 2268#2616: *40 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:12 [error] 2268#2616: *41 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:28 [error] 2268#2616: *42 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:29 [error] 2268#2616: *42 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:33 [error] 2268#2616: *45 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "POST /django/dataingester/bhom/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:35 [error] 2268#2616: *47 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:35 [error] 2268#2616: *50 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:36 [error] 2268#2616: *51 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:36 [error] 2268#2616: *53 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:37 [error] 2268#2616: *54 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:37 [error] 2268#2616: *55 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:38 [error] 2268#2616: *57 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:38 [error] 2268#2616: *60 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:49:38 [error] 2268#2616: *61 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:02 [error] 3008#2256: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://[::1]:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:03 [error] 3008#2256: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://127.0.0.1:8001/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:03 [error] 3008#2256: *12 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:03 [error] 3008#2256: *13 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:03 [error] 3008#2256: *15 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:03 [error] 3008#2256: *17 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:04 [error] 3008#2256: *19 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:04 [error] 3008#2256: *23 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:04 [error] 3008#2256: *24 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 13:56:05 [error] 3008#2256: *25 no live upstreams while connecting to upstream, client: 192.168.59.14, server: localhost, request: "GET /django/dataingester/bhom/close/ HTTP/1.1", upstream: "http://localhost/django/dataingester/bhom/close/", host: "mobility358-di.trybmc.com", referrer: "https://mobility358-di.trybmc.com/"
2022/06/02 14:14:51 [error] 3180#3244: *67 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility358-di.trybmc.com"
2022/06/02 14:14:53 [error] 3180#3244: *69 directory index of "C:\Users\Administrator\Desktop\DataIngester\Frontend\dataingester\build/" is forbidden, client: 192.168.59.14, server: localhost, request: "GET / HTTP/1.1", host: "mobility358-di.trybmc.com"
